browser = Chrome
username = autoscript@test.com
password = AutoTest@1234
headless = true
url = https://naveenautomationlabs.com/opencart/index.php?route=account/login
incognito = true
highlight = true
